# Generated by Django 4.2.23 on 2025-06-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('ubicacion', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('numero_viviendas', models.IntegerField(max_length=50)),
                ('numero_parques', models.IntegerField(max_length=50)),
                ('numero_edificios', models.IntegerField(max_length=50)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenamiento.parroquia')),
            ],
        ),
    ]
