# Generated by Django 4.2.23 on 2025-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='numero_edificios',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='numero_parques',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='numero_viviendas',
            field=models.IntegerField(),
        ),
    ]
